### ISSUE TITLE
Package name causes issues on Package Control

### ISSUE THREAD

**Issue by FichteFoll** [colinta/decent-swift-syntax#20]
The package uses an asterisk character in its package name on Package Control which causes issues, specifically in that it is uninstallable on Windows because `*` are invalid in file paths.

We do actually check for these in our repo tests, but because you added the package in a custom repo and we don't fetch these for the automated tests (only for manual runs), this was missed.

Please rename the package.

**Comment by colinta** [comment]
Yeah I’ve meant to rename it for a long time... will do.

**Comment by FichteFoll** [comment]
Did you perhaps forget to add a `previous_names` entry for the renamed package? https://packagecontrol.io/packages/Swift%20for%20F*ing%20Sublime still exists.

**Comment by colinta** [comment]
Ah I didn’t know that was an option.

**Comment by colinta** [comment]
OK [this commit](d0213b3) should do it.
