### ISSUE TITLE
Missing preprocessor tokens

### ISSUE THREAD

**Issue by rwols** [colinta/decent-swift-syntax#25]
Handling of preprocessor tokens is missing:

<img width="230" alt="image" src="https://user-images.githubusercontent.com/2431823/95656104-48926980-0b0c-11eb-91e2-30479b97ad4e.png">

**Comment by colinta** [comment]
![Screen Shot 2020-10-12 at 9 53 34 AM](https://user-images.githubusercontent.com/27570/95754309-d71ffb80-0c70-11eb-98fa-9cb87a3f247b.png)

The `#` is being marked as `punctuation.definition.preprocessor` (I'll addd `meta.preprocessor.swift` here) and the `if/endif` are being marked as `meta.preprocessor.c` (I'll change this to `meta.preprocessor.swift`), which in my color scheme look like the above.

**Comment by rwols** [comment]
The `meta` scopes are not supposed to be highlighted by a .sublime-color-scheme. The C syntax uses `keyword.control` for all of these preprocessor keywords. Consider adding `keyword.control` for Swift, too.

**Comment by colinta** [comment]
I followed the guidelines at https://www.sublimetext.com/docs/scope_naming.html#meta - and [zenburn](https://github.com/colinta/zenburn) works well for me.  A PR is welcome, but I don't have a way of testing these changes, and so I don't have an easy path to implement them.
