### ISSUE TITLE
String with leading period doesn't highlight correctly

### ISSUE THREAD

**Issue by akrabat** [colinta/decent-swift-syntax#7]
``` swift
let test= ".gitignore"
```

doesn't highlight correctly. The opening double quotes are ignored and so the closing ones are treated as opening which makes the rest of the file seem to be part of the string!

**Comment by colinta** [comment]
Yeah I tried to figure this out, and was stumped.  Known issue.

**Comment by colinta** [comment]
This seems to have been resolved at some point.  🎉
